export const createPageTemplate = (
    name: string
): string => `// import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/${name}.module.css"
import Layout from "../components/Layout/Layout"
import type { ReactElement } from "react"
import type { NextPageWithLayout } from "./_app"

const ${name}: NextPageWithLayout = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Notion Flashcard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>
                    Notion Flashcard
                </h1>

            </main>

        </div>
    )
}

${name}.getLayout = function getLayout(page: ReactElement) {
    return (
        <Layout>
            {page}
        </Layout>
    )
}

export default ${name}
`

export const createStyleTemplate = (): string => `.container {
	width: 500px;
	background-color: pink
}
`