import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Card from "../components/Card"
import { useState } from "react"
import posts from "../lib/notion"

export async function getServerSideProps() {
    // Get the posts
    let  results = await posts()
    // Return the result
    return {
        props: {
            posts: results || null
        }
    }
}

interface Props {
	posts: any
}

const Home: NextPage<Props> = ({ posts }) => {
	  const [postIndex, setPostIndex] = useState<number>(0)

	  const displayPosts = posts.results.map((post: { properties: { Name: any; Description: any } }) => 
        ({
            title: post.properties.Name.title[0].plain_text,
            description: post.properties.Description.rich_text[0].plain_text
        })
    )

    const postLength = displayPosts.length

    // const displayPosts = posts

    console.log(displayPosts)
    // console.log(displayPosts[1].description)
    const [title, setTitle] = useState(displayPosts[postIndex].title)
    const [description, setDescription] = useState(displayPosts[postIndex].description)
    const [ifFlipped, setIfFlipped] = useState(false)

    const flipCard = () => {
        setIfFlipped((prev) => !prev)
    }

    const setNewCard = (index: number) => {
        setTitle(displayPosts[index].title)
        setDescription(displayPosts[index].description)
    }

    const indexIncrement = () => 
        setPostIndex((prev) => prev + 1)
    

    const handleClick = () => {
        flipCard()
    }

    const handleNextButton = () => {
        if (postIndex < postLength - 1) {
            indexIncrement()
            console.log(postIndex)
            setIfFlipped(false)
            setNewCard(postIndex + 1)
        } else {
            setTitle("Congrats!!")
        }
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Notion Flashcard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Notion Flashcard
                </h1>

                <p className={styles.description}>
                    {postIndex + 1} / {postLength}
                </p>

                <div className={styles.grid}>
                    <Card 
                        title={title} 
                        description={description} 
                        ifFlipped={ifFlipped}
                        onClick={handleClick}
                    />
                </div>
                <button className={styles.button}
                    onClick={handleNextButton}>Next</button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
