import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Card from "../components/Card"
import { useState } from "react"
import { queryDatabases } from "../lib/notion"

export async function getServerSideProps() {
    const results = await queryDatabases()
    return {
        props: {
            contents: results || null
        }
    }
}

interface Props {
	contents: any
}

const Home: NextPage<Props> = ({ contents }) => {
	  const [contentIndex, setContentIndex] = useState<number>(0)

	  const displayContents = contents.results.map((content: { properties: { Name: any; Description: any } }) => 
        ({
            title: content.properties.Name.title[0].plain_text,
            description: content.properties.Description.rich_text[0].plain_text
        })
    )

    const contentsLength = displayContents.length

    const [title, setTitle] = useState(displayContents[contentIndex].title)
    const [description, setDescription] = useState(displayContents[contentIndex].description)
    const [ifFlipped, setIfFlipped] = useState(false)

    const flipCard = () => {
        setIfFlipped((prev) => !prev)
    }

    const setNewCard = (index: number) => {
        setTitle(displayContents[index].title)
        setDescription(displayContents[index].description)
    }

    const indexIncrement = () => 
        setContentIndex((prev) => prev + 1)
    

    const handleClick = () => {
        flipCard()
    }

    const handleNextButton = () => {
        if (contentIndex < contentsLength - 1) {
            indexIncrement()
            console.log(contentIndex)
            setIfFlipped(false)
            setNewCard(contentIndex + 1)
        } else {
            setTitle("Congrats!!")
        }
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Notion Flashcard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Notion Flashcard
                </h1>

                <p className={styles.description}>
                    {contentIndex + 1} / {contentsLength}
                </p>

                <div className={styles.grid}>
                    <Card 
                        title={title} 
                        description={description} 
                        ifFlipped={ifFlipped}
                        onClick={handleClick}
                    />
                </div>
                <button className={styles.button}
                    onClick={handleNextButton}>Next</button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
